#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# decode_template.py: decode Tasmota device templates and rule on whether the device fits a
# TYWE2L replacement board.
#
# Decode tables are read from tables/tasmota-<sha>.json, generated by extract_tables.py from
# a pinned Tasmota commit. Nothing here is typed from memory, and the Tasmota commit behind
# every decode is printed and carried into the --json output.
#
# Attribution, per tools/tasmota-import/README.md section 2: the decode tables are derived
# from Tasmota (https://github.com/arendst/Tasmota), GPL-3.0, by Theo Arends and
# contributors. See docs/tasmota-import.md section 6 for the licence discussion.
#
# Two things this tool exists to get right, both of which have already bitten someone:
#
#   1. enum UserSelectablePins carries inline "#ifdef ESP32" blocks, so 204 names have a
#      different ordinal on ESP32 than on ESP8266 (docs/tasmota-import.md section 1.3).
#      Every ESP8285 template is decoded against the ESP8266 arm, and --show-esp32-trap
#      prints what the wrong table would have claimed.
#   2. Legacy 8-bit templates and modern packed templates look alike. Encoding is detected
#      with Tasmota's own test from JsonTemplate() so that we never disagree with Tasmota
#      about what a string means.

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_BOARD = HERE / "boards" / "tywe2l-h2.json"

VERDICT_COMPATIBLE = "COMPATIBLE"
VERDICT_TEST_PADS = "NEEDS TEST PADS"
VERDICT_INCOMPATIBLE = "INCOMPATIBLE"
VERDICT_ERROR = "ERROR"

# Role classification, derived from the code name rather than from a hand-typed table of
# ordinals. Outcomes are A (auto-convert), H (needs a human decision) and X (cannot support),
# per docs/tasmota-import.md section 3.2.
# Two-wire LED driver ICs. A device using one of these does not drive its LEDs from the
# module at all: the module clocks a bespoke serial protocol into a constant-current driver
# chip, usually on a separate LED board. That is a different driver architecture from direct
# PWM and it needs different firmware, so it is classified separately rather than lumped in
# with "unsupported". The chip name comes from the Tasmota code name itself, so a chip added
# to a future Tasmota is picked up without editing this list.
LED_DRIVER_CODE = re.compile(
    r"^GPIO_(?P<chip>SM\d+[A-Z]*|BP\d+[A-Z]*|P9813|MY92\w*)_(CLK|DAT|SEL|DIN)$"
)
# MY92x1 spells its two pins DI and DCKI rather than <chip>_CLK and <chip>_DAT.
MY92X1_CODES = {"GPIO_DI": "MY92x1", "GPIO_DCKI": "MY92x1"}

ROLE_RULES = [
    ("GPIO_REL", "relay", "A", "mains or load relay output"),
    ("GPIO_KEY", "button", "A", "momentary pushbutton input"),
    ("GPIO_SWT", "switch", "H", "maintained switch input; switch mode is not in the template"),
    ("GPIO_LEDLNK", "status_led", "A", "link or status LED, Wi-Fi state in Tasmota"),
    ("GPIO_LED", "led", "A", "indicator LED mirroring a relay by index"),
    ("GPIO_PWM", "pwm", "H", "PWM channel; colour, frequency and dimmer range are not in the template"),
    ("GPIO_BUZZER", "buzzer", "H", "buzzer output; no natural Matter cluster"),
    ("GPIO_CNTR", "counter", "H", "pulse counter input"),
    ("GPIO_OUTPUT_HI", "fixed_output", "A", "fixed output, driven high at boot"),
    ("GPIO_OUTPUT_LO", "fixed_output", "A", "fixed output, driven low at boot"),
    ("GPIO_INPUT", "input", "H", "plain digital input"),
    ("GPIO_ADC", "analogue", "X", "analogue input on ADC0/TOUT, which the TYWE2L does not bring out"),
    ("GPIO_TUYA", "tuya_mcu", "X", "TuyaMCU serial link; the device's brain is a separate MCU"),
    ("GPIO_SBR", "serial_bridge", "X", "serial bridge"),
    ("GPIO_TXD", "serial", "X", "raw serial"),
    ("GPIO_RXD", "serial", "X", "raw serial"),
    ("GPIO_WS2812", "addressable_led", "X", "addressable LED string"),
    ("GPIO_IRSEND", "ir", "X", "IR blaster"),
    ("GPIO_IRRECV", "ir", "X", "IR receiver"),
    ("GPIO_RFSEND", "rf", "X", "433 MHz transmitter"),
    ("GPIO_RFRECV", "rf", "X", "433 MHz receiver"),
    ("GPIO_I2C_", "i2c", "H", "software I2C; what is on the bus is not in the template"),
]


class TemplateError(Exception):
    """A template we refuse to decode. Never degraded into a silently free pin."""


def find_tables(explicit: Path | None) -> Path:
    if explicit is not None:
        return explicit
    candidates = sorted((HERE / "tables").glob("tasmota-*.json"))
    if not candidates:
        raise TemplateError(
            "no decode tables found; run extract_tables.py to generate tables/tasmota-<sha>.json"
        )
    if len(candidates) > 1:
        raise TemplateError(
            "several table files present, pass --tables to choose: "
            + ", ".join(candidate.name for candidate in candidates)
        )
    return candidates[0]


class Decoder:
    def __init__(self, tables: dict, board: dict):
        self.tables = tables
        self.board = board
        self.shift = tables["agpio_shift"]
        self.user_ordinal = tables["gpio_user_ordinal"]
        self.esp8266 = tables["user_selectable_pins"]["esp8266"]
        self.esp32 = tables["user_selectable_pins"]["esp32"]
        self.by_ordinal = {ordinal: name for name, ordinal in self.esp8266.items()}
        self.esp32_by_ordinal = {ordinal: name for name, ordinal in self.esp32.items()}
        self.labels = tables["sensor_names"]["esp8266"]
        self.indexed = set(tables["indexed_names"])
        self.convert = tables["gpio_convert"]
        self.slot_to_gpio = tables["esp8266_slot_to_gpio"]
        self.modules = {entry["base"]: entry for entry in tables["supported_modules_esp8266"]}

        self.legs = {leg["esp8285_gpio"]: leg for leg in board["legs"]}
        self.test_pads = {pad["esp8285_gpio"]: pad for pad in board["test_pads"]}
        self.unavailable = {entry["esp8285_gpio"]: entry for entry in board["unavailable"]}

    # -- Tasmota's own conversions -------------------------------------------------------

    def gpio_convert(self, value: int) -> int:
        """GpioConvert() in tasmota/tasmota_support/support.ino."""
        if value >= len(self.convert):
            return self.user_ordinal << self.shift
        return self.convert[value]

    def adc0_convert(self, flag: int) -> int:
        """Adc0Convert() in tasmota/tasmota_support/support.ino."""
        adc0 = flag & 0x0F
        if adc0 > 7:
            return self.user_ordinal << self.shift
        if adc0 == 0:
            return 0
        return (self.esp8266["GPIO_ADC_INPUT"] + adc0 - 1) << self.shift

    # -- Decoding ------------------------------------------------------------------------

    def detect_encoding(self, gpio: list[int]) -> tuple[str, str]:
        """Tasmota's exact test, from JsonTemplate() in support.ino.

        Thirteen elements and every one of them below 256 means the legacy 8-bit encoding.
        Anything else with fourteen elements is the modern packed encoding. Array length
        alone is not the rule: a 13-element array holding a value above 255 is not a legacy
        template, and Tasmota treats it as modern.
        """
        if len(gpio) == 13:
            last = 0
            for value in gpio:
                last = value
                if value > 255:
                    break
            if last < 256:
                return (
                    "legacy",
                    "13 entries and every value below 256, which is Tasmota's own test in "
                    "JsonTemplate() (tasmota/tasmota_support/support.ino)",
                )
            return (
                "modern",
                "13 entries but a value above 255, so Tasmota's legacy test fails and the "
                "array is read as modern packed values",
            )
        if len(gpio) == 14:
            return (
                "modern",
                "14 entries, which only the modern packed encoding has (the fourteenth slot "
                "is ADC0, added in Tasmota 9.1.0)",
            )
        raise TemplateError(
            f"GPIO array has {len(gpio)} entries; an ESP8266/ESP8285 template has 13 (legacy) "
            "or 14 (modern). ESP32-family templates are a different platform and out of scope "
            "(docs/tasmota-import.md section 1.2)"
        )

    def describe_code(self, packed: int) -> dict:
        """Split a packed value into function, instance index, name and label."""
        if packed == 0:
            return {
                "code": "GPIO_NONE",
                "label": "None",
                "index": None,
                "role": "none",
                "outcome": "A",
                "description": "deliberately unused",
                "assigned": False,
            }
        ordinal, index = packed >> self.shift, packed & ((1 << self.shift) - 1)
        if ordinal == self.user_ordinal:
            return {
                "code": "GPIO_USER",
                "label": "User",
                "index": None,
                "role": "user",
                "outcome": "A",
                "description": "user configurable, nothing connected",
                "assigned": False,
            }
        name = self.by_ordinal.get(ordinal)
        if name is None:
            raise TemplateError(
                f"packed value {packed} decodes to function ordinal {ordinal}, which is not in "
                f"the ESP8266 arm of UserSelectablePins at Tasmota "
                f"{self.tables['tasmota_commit'][:12]}. An unrecognised code is a hard failure, "
                "never a free pin (docs/tasmota-import.md section 1.7)"
            )
        label = self.labels[ordinal] if ordinal < len(self.labels) else name
        if name in self.indexed:
            label = (
                label.replace("_", str(index + 1), 1)
                if "_" in label
                else f"{label}{index + 1}"
            )
        role, outcome, description, chip = self.classify(name)
        entry = {
            "code": name,
            "label": label,
            "index": index,
            "role": role,
            "outcome": outcome,
            "description": self.polarity_note(name, description),
            "assigned": True,
        }
        if chip:
            entry["driver_chip"] = chip
        return entry

    @staticmethod
    def classify(name: str) -> tuple[str, str, str, str | None]:
        chip = MY92X1_CODES.get(name)
        if chip is None:
            match = LED_DRIVER_CODE.match(name)
            chip = match.group("chip") if match else None
        if chip:
            return (
                "led_driver",
                "X",
                f"two-wire {chip} LED driver IC; the module clocks a serial protocol into a "
                "driver chip rather than driving the LEDs itself",
                chip,
            )
        for prefix, role, outcome, description in ROLE_RULES:
            if name.startswith(prefix):
                return role, outcome, description, None
        return "other", "X", "not in the supported set for this board", None

    @staticmethod
    def polarity_note(name: str, description: str) -> str:
        notes = []
        if name.endswith("_INV") or "_INV_" in name or name.endswith("_i"):
            notes.append("active low (inverted)")
        if name.endswith("_NP"):
            notes.append("no internal pull-up")
        return description + (", " + ", ".join(notes) if notes else "")

    def esp32_trap(self, packed: int) -> str | None:
        """What the ESP32 arm of the enum would have claimed for the same value."""
        if packed in (0, self.user_ordinal << self.shift):
            return None
        wrong = self.esp32_by_ordinal.get(packed >> self.shift)
        right = self.by_ordinal.get(packed >> self.shift)
        return wrong if wrong and wrong != right else None

    def decode(self, raw: str) -> dict:
        result = {
            "input": raw,
            "tasmota_commit": self.tables["tasmota_commit"],
            "board": self.board["board"],
            "pin_mapping_version": self.board["pin_mapping_version"],
            "errors": [],
            "warnings": [],
        }
        try:
            template = json.loads(raw)
        except json.JSONDecodeError as error:
            result["verdict"] = VERDICT_ERROR
            result["errors"].append(f"not valid JSON: {error}")
            return result
        if not isinstance(template, dict):
            result["verdict"] = VERDICT_ERROR
            result["errors"].append("template is not a JSON object")
            return result

        result["name"] = template.get("NAME")
        gpio = template.get("GPIO")
        if not isinstance(gpio, list) or not all(isinstance(v, int) for v in gpio):
            result["verdict"] = VERDICT_ERROR
            result["errors"].append("GPIO must be an array of integers")
            return result
        if any(value < 0 or value > 0xFFFF for value in gpio):
            result["verdict"] = VERDICT_ERROR
            result["errors"].append("GPIO values must fit in 16 bits")
            return result

        arch = template.get("ARCH")
        if arch is not None and str(arch).upper() not in ("ESP8266", "ESP8285"):
            result["verdict"] = VERDICT_ERROR
            result["errors"].append(
                f"ARCH is {arch!r}; this decoder only handles ESP8266/ESP8285 templates"
            )
            return result

        flag = template.get("FLAG", 0)
        base = template.get("BASE", 18)
        result["flag"] = flag
        result["base"] = base
        module = self.modules.get(base)
        result["base_name"] = module["name"] if module else None
        if template.get("CMND"):
            result["warnings"].append(
                "template carries a CMND backlog; it is copied verbatim for a human and never "
                f"interpreted: {template['CMND']!r}"
            )

        try:
            encoding, how = self.detect_encoding(gpio)
            result["encoding"] = encoding
            result["encoding_detected_by"] = how
            packed = self.to_packed(gpio, encoding, flag, result)
            result["pins"] = self.build_pins(packed)
        except TemplateError as error:
            result["verdict"] = VERDICT_ERROR
            result["errors"].append(str(error))
            return result

        self.verdict(result)
        return result

    def to_packed(self, gpio: list[int], encoding: str, flag, result: dict) -> list[int]:
        if encoding == "legacy":
            if not isinstance(flag, int):
                raise TemplateError("FLAG must be an integer in a legacy template")
            packed = [self.gpio_convert(value) for value in gpio]
            adc0 = self.adc0_convert(flag)
            packed.append(adc0)
            if adc0 != 0:
                result["warnings"].append(
                    f"legacy FLAG {flag} puts a function on ADC0/TOUT; the TYWE2L does not "
                    "bring TOUT out (docs/tasmota-import.md section 1.6)"
                )
            return packed
        packed = [
            (self.user_ordinal << self.shift) if value == 1 else value for value in gpio
        ]
        while len(packed) < 14:
            packed.append(0)
        if isinstance(flag, int) and flag != 0:
            result["warnings"].append(
                f"FLAG is {flag} in a modern template, where it is unused "
                "(GPIO_FLAG_USED is 0 in tasmota_template.h); ignored"
            )
        return packed

    def build_pins(self, packed: list[int]) -> list[dict]:
        pins = []
        for slot, value in enumerate(packed):
            gpio_number = self.slot_to_gpio[slot]
            entry = self.describe_code(value)
            entry.update(
                {
                    "slot": slot,
                    "esp8285_gpio": gpio_number,
                    "esp8285_pin": "ADC0" if gpio_number == -1 else f"GPIO{gpio_number}",
                    "raw": value,
                }
            )
            entry["availability"], entry["availability_note"] = self.availability(gpio_number)
            leg = self.legs.get(gpio_number)
            if leg is not None:
                entry["leg"] = leg["leg"]
                entry["pad"] = leg["pad"]
                entry["h2_gpio"] = leg["h2_gpio"]
            trap = self.esp32_trap(value)
            if trap:
                entry["esp32_table_would_say"] = trap
            pins.append(entry)
        return pins

    def availability(self, gpio_number: int) -> tuple[str, str]:
        if gpio_number in self.legs:
            leg = self.legs[gpio_number]
            return "leg", f"leg {leg['leg']} (pad {leg['pad']}) to H2 GPIO{leg['h2_gpio']}"
        if gpio_number in self.test_pads:
            pad = self.test_pads[gpio_number]
            return "test_pad", f"{pad['where']} ({pad['label']}), not a leg"
        entry = self.unavailable.get(gpio_number)
        return "unavailable", entry["reason"] if entry else "not brought out on the TYWE2L"

    # -- The verdict ---------------------------------------------------------------------

    @staticmethod
    def driver_architecture(assigned: list[dict]) -> dict:
        """How the device drives its load, which decides which firmware it needs.

        A device can fit the board perfectly and still need completely different firmware,
        so this is a first-class attribute rather than a note. The values are the ones the
        profile schema should carry (docs/flasher-and-registry.md needs revising to hold it).
        """
        chips = sorted({pin["driver_chip"] for pin in assigned if pin.get("driver_chip")})
        families = []
        if chips:
            families.append("two_wire_led_driver")
        if any(pin["role"] == "pwm" for pin in assigned):
            families.append("pwm_direct")
        if any(pin["role"] == "addressable_led" for pin in assigned):
            families.append("addressable_led")
        if any(pin["role"] in ("relay", "led", "status_led", "buzzer", "fixed_output") for pin in assigned):
            families.append("gpio_direct")
        if not families:
            architecture = "none" if not assigned else "input_only"
        elif len(families) == 1:
            architecture = families[0]
        else:
            architecture = "mixed"
        return {
            "driver_architecture": architecture,
            "driver_families": families,
            "driver_chips": chips,
            "pwm_channels": sum(1 for pin in assigned if pin["role"] == "pwm"),
            "relay_count": sum(1 for pin in assigned if pin["role"] == "relay"),
            "button_count": sum(1 for pin in assigned if pin["role"] == "button"),
        }

    def verdict(self, result: dict) -> None:
        assigned = [pin for pin in result["pins"] if pin["assigned"]]
        result["assigned_count"] = len(assigned)
        result.update(self.driver_architecture(assigned))

        blockers, cautions = [], []
        unavailable = [pin for pin in assigned if pin["availability"] == "unavailable"]
        test_pads = [pin for pin in assigned if pin["availability"] == "test_pad"]

        for pin in unavailable:
            blockers.append(
                f"{pin['esp8285_pin']} carries {pin['label']} and {pin['availability_note']}"
            )
        for pin in test_pads:
            cautions.append(
                f"{pin['esp8285_pin']} carries {pin['label']} on a {pin['availability_note']}"
            )

        # Firmware capability is a separate axis from pin fit. A device can land every
        # function on a leg and still need firmware we do not have, which is exactly the
        # two-wire LED driver case, so those are kept out of the pin verdict.
        firmware_blockers = []
        for pin in assigned:
            if pin["outcome"] != "X" or pin in unavailable:
                continue
            firmware_blockers.append(
                f"{pin['esp8285_pin']} uses {pin['code']} ({pin['description']}), which no "
                "current firmware variant supports"
            )

        if result["base"] not in self.board["allowed_base"]:
            name = result["base_name"] or "unknown"
            note = (
                f"BASE is {result['base']} ({name}), not 18 (Generic). A non-generic base "
                "selects a built-in module's driver behaviour"
            )
            if result["base"] == 54:
                note += ", and TuyaMCU devices are a serial-bridge architecture we cannot serve"
            firmware_blockers.append(note)

        if unavailable:
            cautions.append(
                "a device that puts a function on a pin the TYWE2L does not bring out is "
                "almost certainly built on a larger module (TYWE3S or an ESP-12 family part), "
                "so the pin map is right about function and useless about placement "
                "(docs/tasmota-import.md section 4.6)"
            )
        if test_pads:
            cautions.append(
                "the rear test pads face the host board on a vertically mounted TYWE2L, so a "
                "function on GPIO0/1/2/3 is evidence that the module is not a TYWE2L; confirm "
                "the part number on the board before going further"
            )

        if not assigned:
            cautions.append("no pin is assigned a function at all")
        elif not any(
            pin["role"]
            in ("relay", "led", "pwm", "status_led", "buzzer", "fixed_output", "led_driver", "addressable_led")
            for pin in assigned
        ):
            cautions.append("no output role is assigned")

        needs_decision = sorted({pin["code"] for pin in assigned if pin["outcome"] == "H"})
        if needs_decision:
            cautions.append(
                "needs a human decision before a profile can be published: "
                + ", ".join(needs_decision)
                + " (docs/tasmota-import.md sections 3.2 and 4.3)"
            )

        # The verdict is about pins and pins only, which is what the board can and cannot
        # physically reach. Firmware capability is reported alongside it as "servable",
        # because the two failure modes have different fixes: one needs a different board,
        # the other needs a different firmware variant.
        if blockers:
            result["verdict"] = VERDICT_INCOMPATIBLE
        elif test_pads:
            result["verdict"] = VERDICT_TEST_PADS
        else:
            result["verdict"] = VERDICT_COMPATIBLE
        result["blockers"] = blockers
        result["firmware_blockers"] = firmware_blockers
        result["servable"] = not blockers and not firmware_blockers
        result["cautions"] = cautions

        result["leg_mapping"] = [
            {
                "leg": pin["leg"],
                "pad": pin["pad"],
                "esp8285_gpio": pin["esp8285_gpio"],
                "h2_gpio": pin["h2_gpio"],
                "code": pin["code"],
                "label": pin["label"],
                "role": pin["role"],
                "index": pin["index"],
            }
            for pin in sorted(
                (pin for pin in assigned if pin["availability"] == "leg"),
                key=lambda pin: pin["leg"],
            )
        ]
        # An incompatible device gets no leg map, in the text report and in --json alike. A
        # consumer that keyed off the mapping without reading the verdict would otherwise
        # build a profile for a retrofit that cannot exist.
        result["leg_mapping_suppressed"] = result["verdict"] == VERDICT_INCOMPATIBLE
        if result["leg_mapping_suppressed"]:
            result["leg_mapping"] = []

        unused_legs = sorted(
            leg["leg"] for gpio, leg in self.legs.items()
            if gpio not in {pin["esp8285_gpio"] for pin in assigned}
        )
        result["unused_legs"] = unused_legs


# -- Reporting ---------------------------------------------------------------------------


def format_report(result: dict, show_trap: bool) -> str:
    lines = []
    name = result.get("name") or "(unnamed)"
    lines.append(f"=== {name} ===")
    lines.append(f"input: {result['input']}")

    if result["verdict"] == VERDICT_ERROR:
        lines.append("")
        lines.append(f"VERDICT: {VERDICT_ERROR}")
        for error in result["errors"]:
            lines.append(f"  - {error}")
        return "\n".join(lines)

    base_name = result.get("base_name") or "unknown"
    lines.append(
        f"BASE {result['base']} ({base_name})   FLAG {result['flag']}   "
        f"encoding: {result['encoding']}"
    )
    lines.append(f"detected by: {result['encoding_detected_by']}")
    lines.append(f"decoded against Tasmota {result['tasmota_commit'][:12]}, ESP8266 arm of UserSelectablePins")
    lines.append("")

    header = f"{'pin':<6} {'slot':>4} {'raw':>6}  {'component':<14} {'code':<22} {'availability':<12} description"
    lines.append(header)
    lines.append("-" * len(header))
    for pin in result["pins"]:
        if not pin["assigned"] and pin["code"] == "GPIO_NONE":
            description = "unused"
        elif not pin["assigned"]:
            description = "free"
        else:
            description = pin["description"]
        lines.append(
            f"{pin['esp8285_pin']:<6} {pin['slot']:>4} {pin['raw']:>6}  "
            f"{pin['label']:<14} {pin['code']:<22} {pin['availability']:<12} {description}"
        )
        if show_trap and pin.get("esp32_table_would_say"):
            lines.append(
                f"{'':<6} {'':>4} {'':>6}  the ESP32 table would call this "
                f"{pin['esp32_table_would_say']}, and would be wrong"
            )

    lines.append("")
    architecture = result["driver_architecture"]
    if result["driver_chips"]:
        architecture += " (" + ", ".join(result["driver_chips"]) + ")"
    if result["pwm_channels"]:
        architecture += f", {result['pwm_channels']} PWM channel(s)"
    lines.append(f"DRIVER ARCHITECTURE: {architecture}")
    lines.append(f"VERDICT (pins): {result['verdict']}")
    lines.append(
        "SERVABLE: yes" if result["servable"] else "SERVABLE: no, see blockers below"
    )
    for blocker in result["blockers"]:
        lines.append(f"  pin blocker:      {blocker}")
    for blocker in result["firmware_blockers"]:
        lines.append(f"  firmware blocker: {blocker}")
    for caution in result["cautions"]:
        lines.append(f"  note:    {caution}")
    for warning in result["warnings"]:
        lines.append(f"  warning: {warning}")

    if result["verdict"] == VERDICT_INCOMPATIBLE:
        lines.append("")
        lines.append(
            "No leg mapping is emitted: this device does not fit the board, so a leg map "
            "would describe a retrofit that cannot be built."
        )
    elif result["leg_mapping"]:
        lines.append("")
        lines.append("Leg mapping under pin mapping v2 (docs/pin-mapping-v2.md):")
        lines.append(f"  {'leg':<4} {'ESP8285':<9} {'H2':<9} function")
        for leg in result["leg_mapping"]:
            index = "" if leg["index"] is None else f" (index {leg['index']})"
            lines.append(
                f"  {leg['leg']:<4} GPIO{leg['esp8285_gpio']:<5} GPIO{leg['h2_gpio']:<5} "
                f"{leg['label']}{index}"
            )
        if result["unused_legs"]:
            lines.append(
                "  legs with no function: "
                + ", ".join(str(leg) for leg in result["unused_legs"])
            )
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Decode Tasmota templates and rule on TYWE2L replacement-board fit.",
        epilog="Decode tables are derived from Tasmota (github.com/arendst/Tasmota), GPL-3.0, "
        "by Theo Arends and contributors. See docs/tasmota-import.md section 6.",
    )
    parser.add_argument("templates", nargs="*", help="Tasmota template JSON strings, or - for stdin")
    parser.add_argument("--tables", type=Path, default=None, help="decode table JSON to use")
    parser.add_argument("--board", type=Path, default=DEFAULT_BOARD, help="board definition JSON")
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    parser.add_argument(
        "--show-esp32-trap",
        action="store_true",
        help="also print what the ESP32 arm of the enum would have claimed for each code",
    )
    args = parser.parse_args(argv)

    raw_inputs: list[str] = []
    for item in args.templates:
        if item == "-":
            raw_inputs.extend(line for line in sys.stdin.read().splitlines() if line.strip())
        else:
            raw_inputs.append(item)
    if not raw_inputs:
        if sys.stdin.isatty():
            parser.error("no templates given")
        raw_inputs = [line for line in sys.stdin.read().splitlines() if line.strip()]

    try:
        tables_path = find_tables(args.tables)
        tables = json.loads(tables_path.read_text(encoding="utf-8"))
        board = json.loads(args.board.read_text(encoding="utf-8"))
    except (TemplateError, OSError, json.JSONDecodeError) as error:
        print(f"decode_template: {error}", file=sys.stderr)
        return 2

    decoder = Decoder(tables, board)
    results = [decoder.decode(raw) for raw in raw_inputs]

    if args.json:
        print(json.dumps(results, indent=2))
    else:
        print(
            "Decode tables from Tasmota (github.com/arendst/Tasmota), GPL-3.0, "
            f"commit {tables['tasmota_commit'][:12]}.\n"
        )
        print("\n\n".join(format_report(result, args.show_esp32_trap) for result in results))

    return 1 if any(result["verdict"] == VERDICT_ERROR for result in results) else 0


if __name__ == "__main__":
    raise SystemExit(main())
